# Generated by Django 3.2.9 on 2021-11-24 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legal_entities', '0001_initial'),
        ('clients', '0002_alter_client_legal_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legal_entities.legalentity', verbose_name='Юридическое лицо'),
        ),
    ]
